### ISSUE TITLE
problem to start…

### ISSUE THREAD

**Issue by MiroslavMatas** [ildarkhasanshin/cuda_google_translator#6]
want to utilize this new tool…
installed requirement (+ reboot machine, + restart CudaText…)
but still get this message…
do I need to change some path somewhere?

![image](https://user-images.githubusercontent.com/42316770/210372213-375fbad8-3b6e-4721-9e91-60fa1bcb5c90.png)

**Comment by Alexey-T** [comment]
You need to find where PIP installed module 'deep_translator' and find all its dependencies. (inside python dir.) then copy all these modules to 'py' dir.

it's for Windows.

**Comment by MiroslavMatas** [comment]
hmmm…
not mentioned at readme : - (
…and have no idea how to get list of dependencies
and than - what folders to copy

**Comment by Alexey-T** [comment]
I found dep's in https://pypi.org/project/deep-translator/#files , in file PKG-INFO
```
Requires-Dist: beautifulsoup4 (>=4.9.1,<5.0.0)
Requires-Dist: requests (>=2.23.0,<3.0.0)
```
2nd lib 'requests' is already in Cud.
1st is not.
get it on pypi.org , see its PKG-INFO too to find its dep's .

we will add the readme info later.

**Comment by MiroslavMatas** [comment]
I am sorry for jumping in…

maybe will be possible to use `sys.path.append()`, or something like absolute path…
not sure if that is accessible on python world
(just to avoid duplication of libraries)
or - `pip install` directly to `CT\py` folder
just a guessing

**Comment by Alexey-T** [comment]
Windows installation info is in readme.txt in my pull-request
https://github.com/ildarkhasanshin/cuda_deep_translator/pull/7
