### ISSUE TITLE
two suggestions - clipboard + message

### ISSUE THREAD

**Issue by MiroslavMatas** [ildarkhasanshin/cuda_google_translator#8]
kindly asking for integrate two additions - clipboard + message
a/ will be possible to add option for add result of translation into clipboard?
b/ will be possible to send result of translation into Messages at Status Bar?

for those - maybe separate config file cuda_deepl_translate .ini/.json at CT\settings, or new section [deepl_trtanslate] at common CT\settings\plugins.ini

to a/ - automatic copy to clipboard will speedup usage of this plugin… (true/false, 0/1)
to b/ - for short sentence (a few words) will be enough to see translation at message center (like a/)

TIA

**Comment by ildarkhasanshin** [comment]
todo

**Comment by ildarkhasanshin** [comment]
done
